### ISSUE TITLE
Change who can and cannot reload the bot (maybe add another env for owner's discord id)

### ISSUE THREAD

**Issue by pizzadeliverymen** [pizzadeliverymen/PizzaBot#5]
```
 * TODO Change who can and cannot reload the bot (maybe add another env for owner's discord id)
```

https://github.com/pizzadeliverymen/PizzaBot/blob/74b27bef9e6984d7011fa676eaf4310a92b3f397/commands/utils/reload.js#L15

**Comment by chethanyadav456** [comment]
I can make the a owner system function where only owner can access the command.
